version: '3.9'

services:
  iris-api:
    build: .
    container_name: iris-fastapi-ml
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app    # bind mount for hot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
